title: Jaime Avendaño # your name (or website title) here
logo: "/images/jaime.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced developer transitioning into a Data Science role.
  <br><br>
  <a href="https://www.linkedin.com/in/jaimeavendano">View My LinkedIn Profile</a>
  <a href="https://www.kaggle.com/javendano585">View My Kaggle Profile</a>
  <a href="https://twitter.com/JaimeAAvendano">Follow my on Twitter</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
